// GENERERT AV scripts/bygg-figurfasit.mjs — IKKE REDIGER FOR HÅND.
//
// Standardfigurene for de atten stjernebildene Lende tegner, hentet fra
// d3-celestials `data/constellations.lines.json` (ofrohn/d3-celestial, BSD-3)
// og slått opp mot HYG for Bayer-betegnelser.
//
// Fasit fra en uavhengig implementasjon bakes INN og hentes ikke: en test som
// krever nett blir skrudd av. Samme grunn som referansepunktene i
// planeter.test.js.
//
// Hvert element er et par av Bayer-betegnelser, sortert alfabetisk og skilt med
// « — ». Komponent-suffiks (`Nu-2` → `Nu`) er strippet.
//
// BRUKEN ER ENSRETTET, og det er hele poenget (se stjerner.test.js): en strek vi
// tegner MÅ finnes her. En strek her som vi IKKE tegner er greit — kjedene våre
// er bevisste forenklinger for en telefonskjerm.
/* eslint-disable */

export const FIGUR_FASIT = {
  "andromeda": [
    "Alp And — Del And",
    "Bet And — Del And",
    "Bet And — Gam And",
    "Bet And — Mu And",
    "Del And — Eps And",
    "Del And — Pi And",
    "Eps And — Zet And",
    "Eta And — Zet And",
    "Iot And — Kap And",
    "Iot And — Omi And",
    "Iot And — Pi And",
    "Kap And — Lam And",
    "Kap And — Psi And",
    "Mu And — Nu And",
    "Nu And — Phi And",
  ],
  "bjornevokteren": [
    "Alp Boo — Eps Boo",
    "Alp Boo — Eta Boo",
    "Alp Boo — Rho Boo",
    "Alp Boo — Zet Boo",
    "Bet Boo — Del Boo",
    "Bet Boo — Gam Boo",
    "Del Boo — Eps Boo",
    "Eta Boo — Tau Boo",
    "Gam Boo — Lam Boo",
    "Gam Boo — Rho Boo",
    "Kap Boo — Lam Boo",
    "Kap Boo — The Boo",
    "Lam Boo — The Boo",
  ],
  "dragen": [
    "Alp Dra — Iot Dra",
    "Alp Dra — Kap Dra",
    "Bet Dra — Gam Dra",
    "Bet Dra — Nu Dra",
    "Chi Dra — Phi Dra",
    "Del Dra — Eps Dra",
    "Del Dra — Phi Dra",
    "Del Dra — Xi Dra",
    "Eta Dra — The Dra",
    "Eta Dra — Zet Dra",
    "Gam Dra — Xi Dra",
    "Iot Dra — The Dra",
    "Kap Dra — Lam Dra",
    "Nu Dra — Xi Dra",
    "Phi Dra — Zet Dra",
  ],
  "karlsvogna": [
    "Alp UMa — Bet UMa",
    "Alp UMa — Del UMa",
    "Bet UMa — Gam UMa",
    "Bet UMa — Phi UMa",
    "Bet UMa — Ups UMa",
    "Chi UMa — Gam UMa",
    "Chi UMa — Nu UMa",
    "Chi UMa — Psi UMa",
    "Del UMa — Eps UMa",
    "Del UMa — Gam UMa",
    "Eps UMa — Zet UMa",
    "Eta UMa — Zet UMa",
    "Iot UMa — The UMa",
    "Kap UMa — The UMa",
    "Lam UMa — Psi UMa",
    "Mu UMa — Psi UMa",
    "Nu UMa — Xi UMa",
    "Omi UMa — Ups UMa",
    "Phi UMa — The UMa",
  ],
  "kassiopeia": [
    "Alp Cas — Bet Cas",
    "Alp Cas — Gam Cas",
    "Del Cas — Eps Cas",
    "Del Cas — Gam Cas",
  ],
  "kefeus": [
    "Alp Cep — Bet Cep",
    "Alp Cep — Eta Cep",
    "Alp Cep — Mu Cep",
    "Bet Cep — Gam Cep",
    "Bet Cep — Iot Cep",
    "Del Cep — Iot Cep",
    "Del Cep — Zet Cep",
    "Eps Cep — Mu Cep",
    "Eps Cep — Zet Cep",
    "Eta Cep — The Cep",
    "Gam Cep — Iot Cep",
  ],
  "kusken": [
    "Alp Aur — Bet Aur",
    "Alp Aur — Del Aur",
    "Alp Aur — Eps Aur",
    "Alp Aur — Eta Aur",
    "Bet Aur — Del Aur",
    "Bet Aur — The Aur",
    "Bet Tau — Iot Aur",
    "Bet Tau — The Aur",
    "Eps Aur — Zet Aur",
    "Eta Aur — Iot Aur",
  ],
  "lille-bjorn": [
    "Alp UMi — Del UMi",
    "Bet UMi — Gam UMi",
    "Bet UMi — Zet UMi",
    "Del UMi — Eps UMi",
    "Eps UMi — Zet UMi",
    "Eta UMi — Gam UMi",
    "Eta UMi — Zet UMi",
  ],
  "lyren": [
    "Alp Lyr — Eps Lyr",
    "Alp Lyr — Zet Lyr",
    "Bet Lyr — Gam Lyr",
    "Bet Lyr — Zet Lyr",
    "Del Lyr — Gam Lyr",
    "Del Lyr — Zet Lyr",
    "Eps Lyr — Zet Lyr",
  ],
  "loven": [
    "Alp Leo — Eta Leo",
    "Alp Leo — The Leo",
    "Bet Leo — Del Leo",
    "Bet Leo — The Leo",
    "Del Leo — Gam Leo",
    "Eps Leo — Mu Leo",
    "Eta Leo — Gam Leo",
    "Gam Leo — Zet Leo",
    "Mu Leo — Zet Leo",
  ],
  "nordlige-krone": [
    "Alp CrB — Bet CrB",
    "Alp CrB — Gam CrB",
    "Bet CrB — The CrB",
    "Del CrB — Eps CrB",
    "Del CrB — Gam CrB",
    "Eps CrB — Iot CrB",
  ],
  "orion": [
    "Alp Ori — Gam Ori",
    "Alp Ori — Lam Ori",
    "Alp Ori — Mu Ori",
    "Alp Ori — Zet Ori",
    "Bet Ori — Eta Ori",
    "Chi Ori — Chi Ori",
    "Chi Ori — Nu Ori",
    "Chi Ori — Xi Ori",
    "Del Ori — Eps Ori",
    "Del Ori — Eta Ori",
    "Del Ori — Gam Ori",
    "Eps Ori — Zet Ori",
    "Gam Ori — Lam Ori",
    "Gam Ori — Pi Ori",
    "Kap Ori — Zet Ori",
    "Mu Ori — Xi Ori",
    "Omi Ori — Pi Ori",
    "Pi Ori — Pi Ori",
  ],
  "pegasus": [
    "Alp And — Bet Peg",
    "Alp And — Gam Peg",
    "Alp Peg — Bet Peg",
    "Alp Peg — Gam Peg",
    "Alp Peg — Xi Peg",
    "Bet Peg — Eta Peg",
    "Bet Peg — Mu Peg",
    "Eps Peg — The Peg",
    "Eta Peg — Pi Peg",
    "Iot Peg — Kap Peg",
    "Iot Peg — Lam Peg",
    "Lam Peg — Mu Peg",
    "The Peg — Zet Peg",
    "Xi Peg — Zet Peg",
  ],
  "persevs": [
    "Alp Per — Gam Per",
    "Alp Per — Psi Per",
    "Bet Per — Kap Per",
    "Bet Per — Ome Per",
    "Del Per — Nu Per",
    "Del Per — Psi Per",
    "Eps Per — Nu Per",
    "Eps Per — Xi Per",
    "Eta Per — Gam Per",
    "Eta Per — Tau Per",
    "Iot Per — Kap Per",
    "Iot Per — Tau Per",
    "Iot Per — The Per",
    "Lam Per — Mu Per",
    "Ome Per — Rho Per",
    "Omi Per — Zet Per",
    "Phi Per — The Per",
    "Pi Per — Rho Per",
    "Xi Per — Zet Per",
  ],
  "svanen": [
    "Alp Cyg — Gam Cyg",
    "Bet Cyg — Eta Cyg",
    "Del Cyg — Gam Cyg",
    "Del Cyg — Iot Cyg",
    "Eps Cyg — Gam Cyg",
    "Eps Cyg — Zet Cyg",
    "Eta Cyg — Gam Cyg",
    "Iot Cyg — Kap Cyg",
  ],
  "tvillingene": [
    "Alp Gem — Bet Gem",
    "Alp Gem — Tau Gem",
    "Bet Gem — Ups Gem",
    "Del Gem — Lam Gem",
    "Del Gem — Ups Gem",
    "Del Gem — Zet Gem",
    "Eps Gem — Mu Gem",
    "Eps Gem — Tau Gem",
    "Eta Gem — Mu Gem",
    "Gam Gem — Xi Gem",
    "Gam Gem — Zet Gem",
  ],
  "tyren": [
    "Alp Tau — The Tau",
    "Alp Tau — Zet Tau",
    "Bet Tau — Eps Tau",
    "Del Tau — Eps Tau",
    "Del Tau — Gam Tau",
    "Gam Tau — Lam Tau",
    "Gam Tau — The Tau",
    "Lam Tau — Xi Tau",
    "Nu Tau — Xi Tau",
    "Omi Tau — Xi Tau",
  ],
  "ornen": [
    "Alp Aql — Bet Aql",
    "Alp Aql — Del Aql",
    "Alp Aql — Gam Aql",
    "Alp Aql — Zet Aql",
    "Bet Aql — The Aql",
    "Del Aql — Eta Aql",
    "Del Aql — Lam Aql",
    "Del Aql — Zet Aql",
    "Eta Aql — The Aql",
  ],
}
